version: "3"

services:
  app:
    build: .
    image: linkedin-automation-app
    volumes:
      - ./:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000